create type "public"."tipo_pago" as enum ('crear_evento', 'destacar_evento');

create table "public"."pagos" (
    "id" bigint generated by default as identity not null,
    "fecha" date not null default now(),
    "hora" time without time zone not null default now(),
    "tipo_pago" tipo_pago not null,
    "id_usuario" uuid not null,
    "total" numeric not null,
    "desglose_costos" jsonb not null
);


alter table "public"."pagos" enable row level security;

CREATE UNIQUE INDEX pagos_pkey ON public.pagos USING btree (id);

alter table "public"."pagos" add constraint "pagos_pkey" PRIMARY KEY using index "pagos_pkey";

alter table "public"."pagos" add constraint "public_pagos_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE not valid;

alter table "public"."pagos" validate constraint "public_pagos_id_usuario_fkey";

grant delete on table "public"."pagos" to "anon";

grant insert on table "public"."pagos" to "anon";

grant references on table "public"."pagos" to "anon";

grant select on table "public"."pagos" to "anon";

grant trigger on table "public"."pagos" to "anon";

grant truncate on table "public"."pagos" to "anon";

grant update on table "public"."pagos" to "anon";

grant delete on table "public"."pagos" to "authenticated";

grant insert on table "public"."pagos" to "authenticated";

grant references on table "public"."pagos" to "authenticated";

grant select on table "public"."pagos" to "authenticated";

grant trigger on table "public"."pagos" to "authenticated";

grant truncate on table "public"."pagos" to "authenticated";

grant update on table "public"."pagos" to "authenticated";

grant delete on table "public"."pagos" to "service_role";

grant insert on table "public"."pagos" to "service_role";

grant references on table "public"."pagos" to "service_role";

grant select on table "public"."pagos" to "service_role";

grant trigger on table "public"."pagos" to "service_role";

grant truncate on table "public"."pagos" to "service_role";

grant update on table "public"."pagos" to "service_role";


